### ISSUE TITLE
Add API documentation with OpenAPI/Swagger

### ISSUE THREAD

**Issue by umanda** [tinithkorala/Ifonix-Back-end#1]
**Describe the bug**
REST API documentation not added.

**To Reproduce**
Not applicable

**Expected behavior**
API should be documented according to OpenAPI/Swagger standards and testers and developers should be able to access the interactive API UI.

**Screenshots**
Not applicable

**Additional context**

https://github.com/tinithkorala/Ifonix-Back-end/blob/6ab7c5facaab69d3ed39cfda09965e67653adce7/routes/api.php#L26

**Comment by tinithkorala** [comment]
Created API documentation according to OpenAPI/Swagger
